[theme]
primaryColor = "#2165D6"
backgroundColor = "#F7F9FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#132238"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

